--liquibase formatted sql
--changeset queryparams:01

create table staff (
    id   number generated by default on null as identity not null enable,
    name varchar2(255 char)
);

alter table staff
    add constraint staff_id_pk primary key ( id )
        using index enable;


create table action_items (
    id     number generated by default on null as identity not null enable,
    name   varchar2(255 char),
    status varchar2(8 byte) default 'OPEN'
);

alter table action_items
    add constraint action_items_con
        check ( status in ( 'OPEN', 'COMPLETE' ) ) enable;

alter table action_items
    add constraint action_id_pk primary key ( id )
        using index enable;

create table action_item_team_members (
    id        number generated by default on null as identity not null enable,
    action_id number,
    user_id   number,
    role      varchar2(6 char) default 'MEMBER'
);

alter table action_item_team_members
    add constraint action_item_team_members_con
        check ( role in ( 'LEAD', 'MEMBER' ) ) enable;

alter table action_item_team_members
    add constraint team_id_pk primary key ( id )
        using index enable;

alter table action_item_team_members
    add constraint team_action_id_fk
        foreign key ( action_id )
            references action_items ( id )
                on delete cascade
        enable;