--liquibase formatted sql
--changeset martincarstenbach:1 failOnError:true labels:tables

create table users (
    id number generated by default on null as identity
    constraint pk_users primary key,
    name varchar2(255) not null
);