--liquibase formatted sql
--changeset martincarstenbach:2 failOnError:true labels:tables

create table categories (
    id number generated by default on null as identity
    constraint pk_categories primary key,
    name varchar2(255) not null,
    prio varchar2(10) default 'low' not null
);

alter table categories add constraint c_priority check (prio in ('low', 'medium', 'high'));