# THIS IS NOT A PRODUCTION SETUP - LAB USE ONLY!
services:
    oracle:

        image: docker.io/gvenzl/oracle-free:23.9
        ports:
            - 1521:1521
        environment:
            - ORACLE_PASSWORD=${ORACLE_PASSWORD:?Please provide a password for the Oracle DBA accounts}
            - APP_USER=demouser
            - APP_USER_PASSWORD=${APP_USER_PASSWORD:?Please provide a password for the application user}
        volumes:
            - oradata-vol:/opt/oracle/oradata
            - ./initialisation:/container-entrypoint-initdb.d:Z
        networks:
            - backend
        healthcheck:
            test: ["CMD", "healthcheck.sh"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s
            start_interval: 5s

    ords:
        depends_on:
            oracle:
                condition: service_healthy
        image: container-registry.oracle.com/database/ords:25.2.3
        environment:
            - DBHOST=oracle
            - DBPORT=1521
            - DBSERVICENAME=freepdb1
            - ORACLE_PWD=${ORACLE_PASSWORD:?Please provide a password for the Oracle DBA accounts}
            - DEBUG=TRUE
        networks:
            - backend
        ports:
            - 8080:8080
            - 8443:8443
            - 27017:27017
        volumes:
            - ords-config-vol:/etc/ords/config
            # use this volume mount for the initial APEX installation
            # - ./apex:/opt/oracle/apex:Z
            # once installed, uncomment the line above and remove the comment from the line below
            # or else you might get runtime errors when patching APEX
            # - ./apex/images:/opt/oracle/apex/images:Z

volumes:
    oradata-vol:
    ords-config-vol:

networks:
    backend: