# THIS IS NOT A PRODUCTION SETUP - LAB USE ONLY!
services:
    oracle:

        image: docker.io/gvenzl/oracle-free:23.9
        ports:
            - 1521:1521
        environment:
            - ORACLE_PASSWORD=${ORACLE_PASSWORD:?Please provide a password for the Oracle DBA accounts}
            - APP_USER=demouser
            - APP_USER_PASSWORD=${APP_USER_PASSWORD:?Please provide a password for the application user}
        volumes:
            - oradata-vol:/opt/oracle/oradata
            - ./initialisation:/container-entrypoint-initdb.d
        networks:
            - backend
        healthcheck:
            test: [ "CMD", "/opt/oracle/checkDBStatus.sh" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s

volumes:
    oradata-vol:

networks:
    backend:
